---
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
    paths:
      - '.github/workflows/github-pages.yaml'
      - 'docs/**'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  # Required for requesting a OIDC JWT, see https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect
  id-token: write
  # pages to trigger a GitHub Pages build
  pages: write

jobs:
  build:
    uses: potherca/hugo-build/.github/workflows/hugo-build.yaml@main
    with:
      # See more build details
      build-log-level: info
      # Use README.md files as folder index
      build-readme-as-index: true
      # Import Hugo module of the "Relearn" theme
      config-module-imports: |
        { "path": "github.com/McShelby/hugo-theme-relearn" }
      # Module mount configuration, For a full list of options see: https://gohugo.io/configuration/module/#mounts
      config-module-mounts: |
        { "source": "img/", "target": "content/reference/img/" },
        { "source": "introduction.md", "target": "content/_index.md" }
      # Theme specific configuration. For a full list of options see:
      # https://mcshelby.github.io/hugo-theme-relearn/configuration/reference/
      config-params: |
        "alwaysopen": false,
        "collapsibleMenu": true,
        "disableGeneratorVersion": true,
        "disableInlineCopyToClipBoard": true,
        "disableLandingPageButton": true,
        "themeVariant": [ "auto", "zen-dark", "zen-light" ]
      # Custom CSS
      css: |
        /* Avoid title being shown twice */
        h1:has(+ h1),
        /* Hide the "Built with Hugo" link */
        p:has(a[href="https://gohugo.io/"]),
        /* Hide duplicate menu items */
        [data-nav-id*="/readme/index.html"] {
          display: none;
        }
      # Configuration in the root of the Hugo config. For a full list of options see: https://gohugo.io/configuration/all/
      config-root-keys: |
        "disableHugoGeneratorInject": true,
        "languageCode": "en-us",
        "markup": { "goldmark": { "renderer": { "unsafe": true } } },
        "title": "MetroJS"
      path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
